Blockchain API and Mosaic API
proximax-storage/cpp-xpx-chain-sdk pull request #11
Opened 2019-07-26 13:20 UTC by vulfke482

Blockchain API: All queries are done, except getting block's transactions, because it needs to implement transaction deserialization.
Mosaic API: Done.

2019-08-06 10:23 UTC, otsybizov commented
Overall, I don't see any benefit of interfaces like IClient, IAccountService etc. You'd better remove them at all.

2019-08-06 15:07 UTC, otsybizov commented on include/nemcpp/client.h
> +	class InvalidJSON : public std::runtime_error {
Please, use camel case. E.g. InvalidJSON -> InvalidJson

2019-08-06 15:07 UTC, otsybizov commented on include/nemcpp/contract/ContractService.h
> +#ifndef NEM2_SDK_CPP_CONTRACTSERVICE_H
Please, use #pragma once instead of inclusion guard.

2019-08-06 15:07 UTC, otsybizov commented on include/nemcpp/model/account/account_property.h
>  	struct AccountProperty {
Class with the same name is already defined above, that's a bit confusing.

2019-08-06 15:07 UTC, otsybizov commented on include/nemcpp/model/account/address.h
>  namespace std {
It is not recommended to extend std namespace.

2019-08-06 15:07 UTC, otsybizov commented on include/nemcpp/model/message/message.h
> +        ByteArray payload; //ByteArray = struct { uint8_t* array, int size;}
Please, use m_ prefix for class member names.

2019-08-06 15:07 UTC, otsybizov commented on include/nemcpp/service/http.h
> +	typedef int StatusCode;
Prefer 'using' to 'typedef'.

2019-08-06 15:07 UTC, otsybizov commented on src/sdk/model/mosaic/mosaic_info.cpp
> +class MosaicSerivice {
What is it for?

2019-08-06 18:18 UTC, pananton commented on include/nemcpp/model/account/address.h
>  namespace std {
C++ standard specifies that it is allowed to extend std namespace _specializing_ existing templates for _user-defined_ types (like std::hash for example, or std::tuple_size). Maybe it's a bad practice for some reason, but I haven't heard about this.

2019-08-07 03:48 UTC, pananton commented on include/nemcpp/model/message/message.h
> +        ByteArray payload; //ByteArray = struct { uint8_t* array, int size;}
Please note, that m_ prefix is not used in existing library types. If you want m_ prefix better to rename members of other classes for consistency (currently data members are named with "_" suffix for private data members and as-is for public struct's data members).

2019-08-09 07:38 UTC, eugene-babichenko commented on include/nemcpp/model/transaction/account_property_transaction_types.h
> +namespace xpx_sdk::difficult_transactions {
maybe `complex_transactions`?

2019-08-09 11:51 UTC, eugene-babichenko requested changes
This pull request is confirmed to be working, so I am not looking deep into the code (I believe that the rest of the team have done so in the previous two weeks). Most of my comments are regarding the code style.

In addition to the code comments I would like to outline the following:

- Please remove the commented pieces of code. If you still need to work on them, move them to a separate branch to make this one clean.
- Provide descriptions for your TODO comments.
- Address pending reviews from this pull request as well as from #7. Implement them, or respond to them, or close the discussions so that I can see there is an agreement.

After that I will consider this pull request ready to merge.

I do not concentrate on the code formatting here. This will be done automatically in a separate pull request.

2019-08-09 11:51 UTC, eugene-babichenko commented on .gitignore
>  _build/
Please remove.

2019-08-09 11:51 UTC, eugene-babichenko commented on .gitignore
> +cmake-build-debug/
Add a newline

2019-08-09 11:51 UTC, eugene-babichenko commented on CMakeLists.txt
> +	add_executable(get_block ${CMAKE_CURRENT_SOURCE_DIR}/examples/get_block.cpp )
Remove whitespace in the end of the line

2019-08-09 11:51 UTC, eugene-babichenko commented on include/nemcpp/client/namespace_service.h
> +//        virtual std::vector<string> getAccountIds(); //maybe in future if will know how to do it
Commits to be merged must not contain commented lines.

2019-08-09 11:51 UTC, eugene-babichenko commented on include/nemcpp/contract/ContractService.h
> +//#include "context.h"
Please remove commented lines or finish working on them.

2019-08-09 11:51 UTC, eugene-babichenko commented on include/nemcpp/model/account/account.h
> +//		Signature cosignAggregateTransaction(const AggregateTransaction* transaction) const;
Please remove commented lines or finish working on them.

2019-08-09 11:51 UTC, eugene-babichenko commented on include/nemcpp/model/transaction/secret_lock_transaction.h
> +//	/// Creates secret lock transaction.
Please remove commented lines or finish working on them.

2019-08-09 11:51 UTC, eugene-babichenko commented on include/nemcpp/model/transaction_simple/aggregate_transaction_types.h
> +//	using EmbeddedTransactions = std::vector<std::shared_ptr<EmbeddedTransaction>>;
Please remove commented lines or finish working on them.

2019-08-09 11:51 UTC, eugene-babichenko commented on src/infrastructure/binary/dto/transaction_dto.h
> +//	using AddressPropertyModificationDTO = TAccountPropertyModificationDTO<AccountAddressProperty::ValueType>;
Please remove commented lines or finish working on them.

2019-08-09 11:51 UTC, eugene-babichenko commented on src/infrastructure/network/http.cpp
> +//		request.set(http::field::body, request_body);
Please remove commented lines or finish working on them.

2019-08-09 11:51 UTC, eugene-babichenko commented on src/infrastructure/network/http.h
> +		PUT
Please add comma in the end. This will provide us clearer diffs in the future

2019-08-09 11:51 UTC, eugene-babichenko commented on src/infrastructure/network/websocket.cpp
> +//#include "websocket.h"
Revert this change.

2019-08-09 11:51 UTC, eugene-babichenko commented on src/infrastructure/network/websocket.h
> +//#pragma once
Revert this change.

2019-08-09 11:51 UTC, eugene-babichenko commented on src/sdk/client/mosaic_service.cpp
> +//	std::string tmp;
Please remove commented lines or finish working on them.

2019-08-09 11:51 UTC, eugene-babichenko commented on src/sdk/client/namespace_service.cpp
> +    std::stringstream path;
Just use strings if the request URL is static. Please also look at other places using using `std::stringstream`.

2019-08-09 11:51 UTC, eugene-babichenko commented on src/sdk/model/account/account.cpp
> +//	Signature Account::cosignAggregateTransaction(const AggregateTransaction* transaction) const
Please remove commented lines or finish working on them.

2019-08-09 11:51 UTC, eugene-babichenko commented on src/sdk/model/transaction/aggregate_transaction.cpp
> +//
what is this for?

2019-08-09 11:51 UTC, eugene-babichenko commented on src/sdk/model/transaction/create_transaction.cpp
> +//using namespace xpx_sdk::difficult_transactions;
Please remove commented lines or finish working on them.

2019-08-12 10:51 UTC, vulfke482 commented on include/nemcpp/client.h
> +	class InvalidJSON : public std::runtime_error {
Done

2019-08-12 10:51 UTC, vulfke482 commented on include/nemcpp/contract/ContractService.h
> +#ifndef NEM2_SDK_CPP_CONTRACTSERVICE_H
I have deleted whole file :)

2019-08-12 10:51 UTC, vulfke482 commented on include/nemcpp/model/account/account_property.h
>  	struct AccountProperty {
They are in different namespaces. Nothing to do with that for now.

2019-08-12 10:51 UTC, vulfke482 commented on include/nemcpp/service/http.h
> +	typedef int StatusCode;
Done

2019-08-12 10:54 UTC, vulfke482 commented on src/sdk/model/mosaic/mosaic_info.cpp
> +class MosaicSerivice {
This file is no longer with us too)

2019-08-12 10:54 UTC, vulfke482 commented on include/nemcpp/model/transaction/account_property_transaction_types.h
> +namespace xpx_sdk::difficult_transactions {
Changed

2019-08-12 10:54 UTC, vulfke482 commented on .gitignore
>  _build/
Removed

2019-08-12 10:55 UTC, vulfke482 commented on .gitignore
> +cmake-build-debug/
Added

2019-08-12 10:55 UTC, vulfke482 commented on CMakeLists.txt
> +	add_executable(get_block ${CMAKE_CURRENT_SOURCE_DIR}/examples/get_block.cpp )
Done

2019-08-12 10:56 UTC, vulfke482 commented on include/nemcpp/contract/ContractService.h
> +//#include "context.h"
Removed whole file)

2019-08-12 10:56 UTC, vulfke482 commented on src/sdk/client/mosaic_service.cpp
> +//	std::string tmp;
Done

2019-08-12 10:57 UTC, vulfke482 commented on src/sdk/client/namespace_service.cpp
> +    std::stringstream path;
Done for all POST requests. GET requests without parameters have been already done in this way.

2019-08-12 10:59 UTC, vulfke482 commented on src/sdk/model/account/account.cpp
> +//	Signature Account::cosignAggregateTransaction(const AggregateTransaction* transaction) const
Removed part was moved to other branch.

2019-08-12 11:00 UTC, vulfke482 commented on src/sdk/model/transaction/aggregate_transaction.cpp
> +//
Removed

2019-08-12 11:00 UTC, vulfke482 commented on src/sdk/model/transaction/create_transaction.cpp
> +//using namespace xpx_sdk::difficult_transactions;
removed

2019-08-14 14:18 UTC, eugene-babichenko commented
From d596666 on macOS

```
7697208349161298311
Mosaic Info: 9000000000000000
1
libc++abi.dylib: terminating with uncaught exception of type xpx_sdk::serialization_error: Exception: Cannot parse JSON. Error with: (/transaction/size)
[1]    3415 abort      ./bin/get_block
```

2019-09-12 08:54 UTC, carlocayos approved these changes

2019-09-12 08:56 UTC, merged